### ISSUE TITLE
v0.2.1: Error on PamGene stage instance

### ISSUE THREAD

**Issue by makostadima** [tercen/export_table_operator#3]
@agouy I tried testing version 0.2.1 on one of the PamGene workflows while I was testing for the Grey Pilgrim release.

Here's the [data step](https://pamgene.tercen.com/myrto.kostadima/w/94e33c1a9fc8c199354fd15723681293/ds/47b68fb1-7c47-4ab9-950c-1d0211d1a033) and here's a screenshot of the error:

<img width="960" alt="image" src="https://github.com/tercen/export_table_operator/assets/1746464/29114b2e-6f66-486e-a476-55b5ce38ef07">

**Comment by agouy** [comment]
Fixed in 0.2.3

**Comment by makostadima** [comment]
@agouy Regarding the new issue I noticed here is some more info:

- When the template workflow (of which the Export Table data step is part) is located in the main project folder then the operator v0.2.3 works as expected --> see example [here](https://pamgene.tercen.com/myrto.kostadima/w/b3839e53255c784b59f1e01fe084a2a8/ds/01b08b92-7ac9-4eeb-9cd7-e2f721982d0c/outTable)
- When the template workflow moves into a subfolder then the same Data step fails. Example [here](https://pamgene.tercen.com/myrto.kostadima/w/94e33c1a9fc8c199354fd15723681293/ds/eadf8ef1-812e-4d49-8c83-371eaf271b80)

What the latest stage version contains is fixing an issue with moving Project contents into subfolders. This feature wasn't working this morning when you created the latest version 0.2.3 of this operator.

**Comment by agouy** [comment]
@amaurel I get this error when I run the data step locally:
![image](https://github.com/tercen/export_table_operator/assets/10561155/69341fe4-c108-4043-99ba-0b98c8eb8ef4)

This is likely not something I can fix in the operator code

**Comment by makostadima** [comment]
@agouy I'm still getting errors when exporting to project.

The issue is in [this line](https://github.com/tercen/export_table_operator/blob/63e155ffab2eeeca4ac0daf99adb152d9cccb4fd/main.R#L72).

From a quick look I had , changing __subfolders__ to __subfolders_list__ would most likely do the trick.

**Comment by agouy** [comment]
Thanks for catching this. Should be fixed in 0.2.5
